# Generated by Django 3.2.15 on 2022-09-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient_filter',
            field=models.CharField(choices=[('vegetables', 'vegetables'), ('eggs', 'eggs'), ('chicken', 'chicken'), ('pasta', 'pasta'), ('fish', 'fish'), ('bread', 'bread'), ('lamb', 'lamb'), ('fruit', 'fruit'), ('beef', 'beef'), ('cheese', 'cheese'), ('pork', 'pork'), ('rice', 'rice'), ('seafood', 'seafood'), ('goose', 'goose'), ('mussels', 'mussels'), ('chocolate', 'chocolate'), ('game', 'game'), ('duck', 'duck')], default='normal', max_length=32),
        ),
    ]
